version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
